#include "medtronic_test.h"

const char *type_string(history_record_type_t t) {
	static char buf[20];
	switch (t) {
	case Bolus:
		return "Bolus";
	case Prime:
		return "Prime";
	case Alarm:
		return "Alarm";
	case DailyTotal:
		return "DailyTotal";
	case BasalProfileBefore:
		return "BasalProfileBefore";
	case BasalProfileAfter:
		return "BasalProfileAfter";
	case BGCapture:
		return "BGCapture";
	case SensorAlarm:
		return "SensorAlarm";
	case ClearAlarm:
		return "ClearAlarm";
	case ChangeBasalPattern:
		return "ChangeBasalPattern";
	case TempBasalDuration:
		return "TempBasalDuration";
	case ChangeTime:
		return "ChangeTime";
	case NewTime:
		return "NewTime";
	case LowBattery:
		return "LowBattery";
	case BatteryChange:
		return "BatteryChange";
	case SetAutoOff:
		return "SetAutoOff";
	case PrepareInsulinChange:
		return "PrepareInsulinChange";
	case SuspendPump:
		return "SuspendPump";
	case ResumePump:
		return "ResumePump";
	case SelfTest:
		return "SelfTest";
	case Rewind:
		return "Rewind";
	case ClearSettings:
		return "ClearSettings";
	case EnableChildBlock:
		return "EnableChildBlock";
	case MaxBolus:
		return "MaxBolus";
	case EnableRemote:
		return "EnableRemote";
	case MaxBasal:
		return "MaxBasal";
	case EnableBolusWizard:
		return "EnableBolusWizard";
	case Unknown2E:
		return "Unknown2E";
	case BolusWizard512:
		return "BolusWizard512";
	case UnabsorbedInsulin512:
		return "UnabsorbedInsulin512";
	case ChangeBGReminder:
		return "ChangeBGReminder";
	case SetAlarmClockTime:
		return "SetAlarmClockTime";
	case TempBasalRate:
		return "TempBasalRate";
	case LowReservoir:
		return "LowReservoir";
	case AlarmClock:
		return "AlarmClock";
	case ChangeMeterID:
		return "ChangeMeterID";
	case BGReceived512:
		return "BGReceived512";
	case ConfirmInsulinChange:
		return "ConfirmInsulinChange";
	case SensorStatus:
		return "SensorStatus";
	case EnableMeter:
		return "EnableMeter";
	case BGReceived:
		return "BGReceived";
	case MealMarker:
		return "MealMarker";
	case ExerciseMarker:
		return "ExerciseMarker";
	case InsulinMarker:
		return "InsulinMarker";
	case OtherMarker:
		return "OtherMarker";
	case EnableSensorAutoCal:
		return "EnableSensorAutoCal";
	case ChangeBolusWizardSetup:
		return "ChangeBolusWizardSetup";
	case SensorSetup:
		return "SensorSetup";
	case Sensor51:
		return "Sensor51";
	case Sensor52:
		return "Sensor52";
	case ChangeSensorAlarm:
		return "ChangeSensorAlarm";
	case Sensor54:
		return "Sensor54";
	case Sensor55:
		return "Sensor55";
	case ChangeSensorAlert:
		return "ChangeSensorAlert";
	case ChangeBolusStep:
		return "ChangeBolusStep";
	case BolusWizardSetup:
		return "BolusWizardSetup";
	case BolusWizard:
		return "BolusWizard";
	case UnabsorbedInsulin:
		return "UnabsorbedInsulin";
	case SaveSettings:
		return "SaveSettings";
	case EnableVariableBolus:
		return "EnableVariableBolus";
	case ChangeEasyBolus:
		return "ChangeEasyBolus";
	case EnableBGReminder:
		return "EnableBGReminder";
	case EnableAlarmClock:
		return "EnableAlarmClock";
	case ChangeTempBasalType:
		return "ChangeTempBasalType";
	case ChangeAlarmType:
		return "ChangeAlarmType";
	case ChangeTimeFormat:
		return "ChangeTimeFormat";
	case ChangeReservoirWarning:
		return "ChangeReservoirWarning";
	case EnableBolusReminder:
		return "EnableBolusReminder";
	case SetBolusReminderTime:
		return "SetBolusReminderTime";
	case DeleteBolusReminderTime:
		return "DeleteBolusReminderTime";
	case BolusReminder:
		return "BolusReminder";
	case DeleteAlarmClockTime:
		return "DeleteAlarmClockTime";
	case DailyTotal515:
		return "DailyTotal515";
	case DailyTotal522:
		return "DailyTotal522";
	case DailyTotal523:
		return "DailyTotal523";
	case ChangeCarbUnits:
		return "ChangeCarbUnits";
	case BasalProfileStart:
		return "BasalProfileStart";
	case ConnectOtherDevices:
		return "ConnectOtherDevices";
	case ChangeOtherDevice:
		return "ChangeOtherDevice";
	case ChangeMarriage:
		return "ChangeMarriage";
	case DeleteOtherDevice:
		return "DeleteOtherDevice";
	case EnableCaptureEvent:
		return "EnableCaptureEvent";
	default:
		sprintf(buf, "Unknown%02X", t);
		return buf;
	}
}
